# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres-volume:
    driver: local


#Что нужно сделать:
#  - Настроить сервисы для:
#      - PostgreSQL (или MySQL) с начальной базой.
#      - Приложения Spring Boot (если нужно).
#  - Открыть нужные порты (например, 5432).
#  - Настроить volume для хранения данных БД.
